### ISSUE TITLE
Slice Extend errors

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#104]
I would like to document ongoing issues with slice extend to verify if those are in fact buggy behaviors or just misunderstanding by the users. Please add to this issue incidents you encounter with as much detail regarding preceding steps by the user as possible.

@mcevik0 @vjorlikowski

**Comment by anriban** [comment]
I encountered it a couple of times in the last week. This is the error I get:

java.lang.Exception: Unable to renew slice: ERROR: renewSlice(): Exception encountered: Slice terms are limited to 336 hours
	at orca.flukes.xmlrpc.OrcaSMXMLRPCProxy.renewSlice(OrcaSMXMLRPCProxy.java:187)
…….

Note that this slice was already extended a few times before this successfully. Then it started throwing this exception. Once it starts throwing this, it will keep throwing this. It also seems that the extend might have worked even if it threw this (from Pequod). When a "View as List" is done on a query for manifest, it shows a stale expiration date. For example, this slice (testSlice-SC16) still says a Jan 31st expiration date. So, there is no way to know what my current expiry date is.

**Comment by mcevik0** [comment]
User (Chuan Li) reported problem on Feb 12th as below:
![screen shot 2017-02-13 at 16 05 16](https://cloud.githubusercontent.com/assets/18286650/22903348/4e748f72-f206-11e6-85d6-8d1f0f3c631a.png)

All reservations were active and already extended until Feb 26th.
```
Reservations for slice dcc22c9d-c274-42b4-bde7-f68b74176895:
93efd576-d2d2-4d77-aa15-b9fd6b8f6694
sl-sm
Slice: dcc22c9d-c274-42b4-bde7-f68b74176895
1
slvmsite.vm [ active, nascent]
Notices: Reservation 93efd576-d2d2-4d77-aa15-b9fd6b8f6694 (Slice con_improve_002) is in state [Active,None]
Start: Sun Feb 12 13:07:30 EST 2017
End: Sun Feb 26 13:13:40 EST 2017
```
User described actions as below:

> From: "Li,Chuan" <lanfker@gmail.com>
> Subject: Re: [GENI-ORCA-USERS] slice renew error. [error message attached]
> Date: February 13, 2017 at 15:27:16 EST
> To: Mert Cevik <mcevik@renci.org>
> Cc: geni-orca-users <geni-orca-users@googlegroups.com>
> 
> Hello Mert,
> 
> Previously, I was unaware of the maximum lifetime constraint on slice, so I tried a longer time than the maximum allowed at first and got an error. I guess besides the error message, the slice was also extended to the maximum lifetime internally somehow. From a user side, I cannot see this success reservation.  When you debug this case, you may try to extend a slice for a very long time for the first trial. This might make this situation come out again. I later tried smaller durations of extension, and they no longer worked.
> 
> Hope this helps.
> 
> Thanks,
> 
> Chuan Li


Actually, this behavior that the user defined looks correct. I tested as below:
1. Create a slice, check reservations: (Valid until Feb 14th)
```
Reservations for slice ae5a4a1b-574d-4c5c-84f3-2fbec6ad34f5:
1547cd2a-dd6b-4583-a553-ced1151ffccd	exo-sm
	Slice: ae5a4a1b-574d-4c5c-84f3-2fbec6ad34f5
	1	bbnvmsite.vm	[ active, nascent]	
	Notices: Reservation 1547cd2a-dd6b-4583-a553-ced1151ffccd (Slice mcevik-fiu-bbn) is in state [Active,None]
	Start: Mon Feb 13 14:00:02 EST 2017	End: Tue Feb 14 14:00:03 EST 2017	Requested end: Tue Feb 14 14:00:03 EST 2017
```
2. Extend reservations for one month and receive error:
![screen shot 2017-02-13 at 16 14 54](https://cloud.githubusercontent.com/assets/18286650/22903726/a2938c24-f207-11e6-897c-9b402565c8b5.png)
3. Check the reservations. (They are already extended for 13 days more, valid until Feb 27th)
```
1547cd2a-dd6b-4583-a553-ced1151ffccd	exo-sm
	Slice: ae5a4a1b-574d-4c5c-84f3-2fbec6ad34f5
	1	bbnvmsite.vm	[ active, nascent]	
	Notices: Reservation 1547cd2a-dd6b-4583-a553-ced1151ffccd (Slice mcevik-fiu-bbn) is in state [Active,None]
	Start: Mon Feb 13 14:00:02 EST 2017	End: Mon Feb 27 16:10:18 EST 2017	Requested end: Mon Feb 27 16:10:18 EST 2017
027e4d11-7d7d-40b7-9184-c0c456235223	exo-sm
```

**Comment by hinchliff** [comment]
The function [OrcaXmlrpcHandler.renewSlice()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.1/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L1874) actually does this almost completely correctly.  It check the renewal end term, and only proceeds if it is valid.  It will automatically change any renewal durations that are greater than the max (two weeks) to be equal to the maximum duration renewal.

The problem comes with a call to [ReservationConverter.setLeaseTerm()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.1/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/ReservationConverter.java#L1984).  This function seems to only verify the Duration with respect to the original Start Date.  This means that any renewals coming in at the maximum will fail here when compared to the original Start Date.

It would be reasonable to update this function to check reservation durations against now(), similar to renewSlice().  However there is not a good way for this function to return errors to renewSlice(), and renewSlice() has already updated several other parts of the reservation that are probably not easy to roll-back if failures occur.

It is more tempting to override the parameter to setLeaseTerm(), currently called `recovery`, to allow the function to bypass validity checks when doing a renewSlice (since the validity has already been verified).  This parameter could be renamed to something like `recoveryOrRenew`.

**Comment by ibaldin** [comment]
I seem to recall this function (on ReservationConverter) was used in different contexts, so the thing to do is to check where else it is called. Either (a) we need to make this function behave consistently in all contexts or (b) split off a version of the function without checks to be used only when called by renewSlice().

**Comment by hinchliff** [comment]
Yes, setLeaseTerm() is currently being called from 3 different places; essentially Create, Recovery, and Renew.

I have not looked extensively into the Create and Recovery use-cases, but the current behavior seems reasonable for both of those.  And it seems reasonable to change the Renew behavior to match the Recovery behavior (where the only difference is that it does not check whether the change in duration is "valid").

But yes, a better solution might be to have all three cases have a sane solution in cases of extreme durations (latest commit).  I _think_ basing the duration comparison against now() will work for the `recovery` case as well as Create and Renew.

**Comment by ibaldin** [comment]
I'm assuming you are referring to the potential difference in the values returned by now() in different calls. In principle, yes, although it seems it may be possible in an extremely rare cases to trigger a problem. Perhaps setLeaseTerm() should not do checking at all. The issue is, 2 week limit is a *controller policy* decision and this part of the code is deeper down and, perhaps, shouldn't be concerned. The checks should be done prior to invoking it and either failing or replacing with controller-imposed deadline that is compliant with the policy...
