### ISSUE TITLE
Intra-domain bandwidth exhaustion behavior

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#36]
This may or may not be a bug. I was testing modify by asking for more resources than available. 

With nodes, the controller properly rejects if the number of nodes exceeds available. With link bandwidth, I asked for a 100G intra-domain link. The controller accepted it, but then the AM properly rejected it. I think it would be better if the controller rejected it at the start? 

This behavior is the same for both modify and create new slice (I tried a new slice with a 100G link with same result). Just wondering why that is.

**Comment by ibaldin** [comment]
@anriban reports issues with accounting XXL VMs and receiving misleading info from broker. This should be looked at after SC.

**Comment by ibaldin** [comment]
Note that while the ticket states initially the problems with MODIFY operation, the bug manifests itself even with simple slice creation. I suggest looking at it first, before testing modify scenarios.

**Comment by hinchliff** [comment]
I don't think I know the best way to fix this yet, but I think the problem is rooted in [CloudHandler:runEmbedding()](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/main/java/orca/embed/cloudembed/controller/CloudHandler.java#L155), and the fact that this function only looks at `request.getTypeTotalUnits()`.  If it looked instead/additionally at `request.getElements()`, it would have access to the number of CPU cores requested.

**Comment by ibaldin** [comment]
?Can you discuss with Yufeng?

**Comment by hinchliff** [comment]
Looking at this problem a little bit deeper, here are a few of the different layers of code where this issue could be addressed:

1. CloudHandler could look at both `request.getTypeTotalUnits` and `request.getElements` in order to calculate whether there were enough resources available.  Similar changes or refactoring of common code would probably also have to be made in [UnboundRequestHandler](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/main/java/orca/embed/cloudembed/controller/UnboundRequestHandler.java#L81).
1. [RequestReservation](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/main/java/orca/embed/policyhelpers/RequestReservation.java) (request) could be modified to have `typeTotalUnits` reflect the CPU count, and not just the VM count.  typeTotalUnits currently gets the unit count from the `DomainResourceType` inside `NetworkElement`.
1. [NetworkElement](https://github.com/RENCI-NRIG/orca5/blob/25c9bf507c47b0785d34b56e389345d4df921eb5/ndl/src/main/java/orca/ndl/elements/NetworkElement.java) could be modified to have its resourceType (DomainResourceType) reflect not the VM count but the CPU count (from the bandwidth `map` of `DomainResource`, also referred to as Constraints.)

I'm still trying to figure out which parts of the code are expecting to find a count of the number of Nodes/VMs, compared to expecting to find a count of the number of CPU cores needed.

It seems like a NetworkElement could/would represent a node/VM.  So you wouldn't expect to get a number for how many Nodes/VMs it represents -- it would always represent exactly one Node/VM.  But there could be a count of CPU cores attached.  Should that CPU count be reflected in `resourceType`?

Should the typeTotalUnits in RequestReservation be a count of Nodes/VMs, or of CPUs?

Do any of these assumptions change if NetworkElement is representing a VLAN instead of a VM?  Would it ever represent more than one VLAN?

**Comment by hinchliff** [comment]
[SimpleVMControl](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/SimpleVMControl.java#L155) is another likely place to look.  The ticket has Properties for the number of CPU Cores / amount of RAM, but the call to [getVMs()](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/SimpleVMControl.java#L182) is not provided with that information.

The one place where this is calculated correctly is in [BrokerSimplerUnitsPolicy](https://github.com/RENCI-NRIG/orca5/blob/25c9bf507c47b0785d34b56e389345d4df921eb5/core/policy/src/main/java/orca/policy/core/BrokerSimplerUnitsPolicy.java#L253).  The properties are sent to [NDLVMInventory](https://github.com/RENCI-NRIG/orca5/blob/25c9bf507c47b0785d34b56e389345d4df921eb5/plugins/ben/src/main/java/orca/plugins/ben/broker/NDLVMInventory.java#L120), where the constraints are checked against available resources.

So, `CloudHandler` is in the Controller?   And `SimpleVMControl` is in the AM?   While `BrokerSimplerUnitsPolicy` is in the Broker?   Where would be the best place to fix this?

**Comment by hinchliff** [comment]
This is the exception I got
```
INFO   | jvm 1    | 2016/12/12 16:54:13 | 2016-12-12 16:54:13,394-[test-ndl-broker]-{ERROR}-orca.test-ndl-broker-(BrokerSimplerUnitsPolicy.java:281)-Failed to ticket: ncsuvmsite.vm for slice: hincha.orca-issue-36.50
INFO   | jvm 1    | 2016/12/12 16:54:13 | java.lang.RuntimeException: Insufficient <memoryCapacity,0> to meet request:12000
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.plugins.ben.broker.NDLVMInventory.allocate(NDLVMInventory.java:111)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.plugins.ben.broker.NDLVMInventory.allocate(NDLVMInventory.java:150)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.policy.core.BrokerSimplerUnitsPolicy.ticket(BrokerSimplerUnitsPolicy.java:271)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.policy.core.BrokerSimplerUnitsPolicy.ticket(BrokerSimplerUnitsPolicy.java:238)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.policy.core.BrokerSimplerUnitsPolicy.allocateTicketing(BrokerSimplerUnitsPolicy.java:153)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.policy.core.BrokerSimplerUnitsPolicy.allocate(BrokerSimplerUnitsPolicy.java:77)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Broker.tickHandler(Broker.java:487)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Actor.actorTick(Actor.java:428)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Actor.access$000(Actor.java:60)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Actor$1.process(Actor.java:333)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Actor.actorMain(Actor.java:377)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at orca.shirako.core.Actor$4.run(Actor.java:1018)
INFO   | jvm 1    | 2016/12/12 16:54:13 |       at java.lang.Thread.run(Thread.java:745)
```

**Comment by hinchliff** [comment]
Anything not specifically about intra-domain bandwidth resources has been moved to a new ticket: #88

My understanding is that for the issue of intra-domain bandwidth resource behavior, the Broker is behaving correctly in issuing tickets in the circumstances described at the top of this issue.  The Broker is not provided with any information about the internal networking, and so cannot deny any requests on the basis of those constraints.
